/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as EntrysRouteImport } from './routes/entrys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as GoalsIndexRouteImport } from './routes/goals.index'
import { Route as EntrysIndexRouteImport } from './routes/entrys.index'
import { Route as SettingsGoalvisibilityRouteImport } from './routes/settings_/goalvisibility'
import { Route as SettingsGoalorderRouteImport } from './routes/settings_/goalorder'
import { Route as GoalsCreateRouteImport } from './routes/goals_/create'
import { Route as GoalsGoalIdRouteImport } from './routes/goals_/$goalId'
import { Route as GoalsGoalIdEditRouteImport } from './routes/goals_/$goalId_.edit'
import { Route as GoalsGoalIdEntriesCreateRouteImport } from './routes/goals_/$goalId_.entries.create'
import { Route as GoalsGoalIdEntriesEntryIdEditRouteImport } from './routes/goals_/$goalId_.entries_.$entryId.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrysRoute = EntrysRouteImport.update({
  id: '/entrys',
  path: '/entrys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GoalsRoute,
} as any)
const EntrysIndexRoute = EntrysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntrysRoute,
} as any)
const SettingsGoalvisibilityRoute = SettingsGoalvisibilityRouteImport.update({
  id: '/settings_/goalvisibility',
  path: '/settings/goalvisibility',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGoalorderRoute = SettingsGoalorderRouteImport.update({
  id: '/settings_/goalorder',
  path: '/settings/goalorder',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsCreateRoute = GoalsCreateRouteImport.update({
  id: '/goals_/create',
  path: '/goals/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/goals_/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdEditRoute = GoalsGoalIdEditRouteImport.update({
  id: '/goals_/$goalId_/edit',
  path: '/goals/$goalId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdEntriesCreateRoute =
  GoalsGoalIdEntriesCreateRouteImport.update({
    id: '/goals_/$goalId_/entries/create',
    path: '/goals/$goalId/entries/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const GoalsGoalIdEntriesEntryIdEditRoute =
  GoalsGoalIdEntriesEntryIdEditRouteImport.update({
    id: '/goals_/$goalId_/entries_/$entryId/edit',
    path: '/goals/$goalId/entries/$entryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrys': typeof EntrysRouteWithChildren
  '/goals': typeof GoalsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals/create': typeof GoalsCreateRoute
  '/settings/goalorder': typeof SettingsGoalorderRoute
  '/settings/goalvisibility': typeof SettingsGoalvisibilityRoute
  '/entrys/': typeof EntrysIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/goals/$goalId/edit': typeof GoalsGoalIdEditRoute
  '/goals/$goalId/entries/create': typeof GoalsGoalIdEntriesCreateRoute
  '/goals/$goalId/entries/$entryId/edit': typeof GoalsGoalIdEntriesEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals/create': typeof GoalsCreateRoute
  '/settings/goalorder': typeof SettingsGoalorderRoute
  '/settings/goalvisibility': typeof SettingsGoalvisibilityRoute
  '/entrys': typeof EntrysIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/goals/$goalId/edit': typeof GoalsGoalIdEditRoute
  '/goals/$goalId/entries/create': typeof GoalsGoalIdEntriesCreateRoute
  '/goals/$goalId/entries/$entryId/edit': typeof GoalsGoalIdEntriesEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrys': typeof EntrysRouteWithChildren
  '/goals': typeof GoalsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/goals_/$goalId': typeof GoalsGoalIdRoute
  '/goals_/create': typeof GoalsCreateRoute
  '/settings_/goalorder': typeof SettingsGoalorderRoute
  '/settings_/goalvisibility': typeof SettingsGoalvisibilityRoute
  '/entrys/': typeof EntrysIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/goals_/$goalId_/edit': typeof GoalsGoalIdEditRoute
  '/goals_/$goalId_/entries/create': typeof GoalsGoalIdEntriesCreateRoute
  '/goals_/$goalId_/entries_/$entryId/edit': typeof GoalsGoalIdEntriesEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrys'
    | '/goals'
    | '/settings'
    | '/goals/$goalId'
    | '/goals/create'
    | '/settings/goalorder'
    | '/settings/goalvisibility'
    | '/entrys/'
    | '/goals/'
    | '/settings/'
    | '/goals/$goalId/edit'
    | '/goals/$goalId/entries/create'
    | '/goals/$goalId/entries/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goals/$goalId'
    | '/goals/create'
    | '/settings/goalorder'
    | '/settings/goalvisibility'
    | '/entrys'
    | '/goals'
    | '/settings'
    | '/goals/$goalId/edit'
    | '/goals/$goalId/entries/create'
    | '/goals/$goalId/entries/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/entrys'
    | '/goals'
    | '/settings'
    | '/goals_/$goalId'
    | '/goals_/create'
    | '/settings_/goalorder'
    | '/settings_/goalvisibility'
    | '/entrys/'
    | '/goals/'
    | '/settings/'
    | '/goals_/$goalId_/edit'
    | '/goals_/$goalId_/entries/create'
    | '/goals_/$goalId_/entries_/$entryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrysRoute: typeof EntrysRouteWithChildren
  GoalsRoute: typeof GoalsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
  GoalsCreateRoute: typeof GoalsCreateRoute
  SettingsGoalorderRoute: typeof SettingsGoalorderRoute
  SettingsGoalvisibilityRoute: typeof SettingsGoalvisibilityRoute
  GoalsGoalIdEditRoute: typeof GoalsGoalIdEditRoute
  GoalsGoalIdEntriesCreateRoute: typeof GoalsGoalIdEntriesCreateRoute
  GoalsGoalIdEntriesEntryIdEditRoute: typeof GoalsGoalIdEntriesEntryIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrys': {
      id: '/entrys'
      path: '/entrys'
      fullPath: '/entrys'
      preLoaderRoute: typeof EntrysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/goals/': {
      id: '/goals/'
      path: '/'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/entrys/': {
      id: '/entrys/'
      path: '/'
      fullPath: '/entrys/'
      preLoaderRoute: typeof EntrysIndexRouteImport
      parentRoute: typeof EntrysRoute
    }
    '/settings_/goalvisibility': {
      id: '/settings_/goalvisibility'
      path: '/settings/goalvisibility'
      fullPath: '/settings/goalvisibility'
      preLoaderRoute: typeof SettingsGoalvisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/goalorder': {
      id: '/settings_/goalorder'
      path: '/settings/goalorder'
      fullPath: '/settings/goalorder'
      preLoaderRoute: typeof SettingsGoalorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/create': {
      id: '/goals_/create'
      path: '/goals/create'
      fullPath: '/goals/create'
      preLoaderRoute: typeof GoalsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/$goalId': {
      id: '/goals_/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/$goalId_/edit': {
      id: '/goals_/$goalId_/edit'
      path: '/goals/$goalId/edit'
      fullPath: '/goals/$goalId/edit'
      preLoaderRoute: typeof GoalsGoalIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/$goalId_/entries/create': {
      id: '/goals_/$goalId_/entries/create'
      path: '/goals/$goalId/entries/create'
      fullPath: '/goals/$goalId/entries/create'
      preLoaderRoute: typeof GoalsGoalIdEntriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/$goalId_/entries_/$entryId/edit': {
      id: '/goals_/$goalId_/entries_/$entryId/edit'
      path: '/goals/$goalId/entries/$entryId/edit'
      fullPath: '/goals/$goalId/entries/$entryId/edit'
      preLoaderRoute: typeof GoalsGoalIdEntriesEntryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EntrysRouteChildren {
  EntrysIndexRoute: typeof EntrysIndexRoute
}

const EntrysRouteChildren: EntrysRouteChildren = {
  EntrysIndexRoute: EntrysIndexRoute,
}

const EntrysRouteWithChildren =
  EntrysRoute._addFileChildren(EntrysRouteChildren)

interface GoalsRouteChildren {
  GoalsIndexRoute: typeof GoalsIndexRoute
}

const GoalsRouteChildren: GoalsRouteChildren = {
  GoalsIndexRoute: GoalsIndexRoute,
}

const GoalsRouteWithChildren = GoalsRoute._addFileChildren(GoalsRouteChildren)

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrysRoute: EntrysRouteWithChildren,
  GoalsRoute: GoalsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  GoalsGoalIdRoute: GoalsGoalIdRoute,
  GoalsCreateRoute: GoalsCreateRoute,
  SettingsGoalorderRoute: SettingsGoalorderRoute,
  SettingsGoalvisibilityRoute: SettingsGoalvisibilityRoute,
  GoalsGoalIdEditRoute: GoalsGoalIdEditRoute,
  GoalsGoalIdEntriesCreateRoute: GoalsGoalIdEntriesCreateRoute,
  GoalsGoalIdEntriesEntryIdEditRoute: GoalsGoalIdEntriesEntryIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
