/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as EntrysRouteImport } from './routes/entrys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as GoalsIndexRouteImport } from './routes/goals.index'
import { Route as EntrysIndexRouteImport } from './routes/entrys.index'
import { Route as SettingsGoalVisibilityRouteImport } from './routes/settings_/goal-visibility'
import { Route as SettingsGoalOrderRouteImport } from './routes/settings_/goal-order'
import { Route as SettingsDeleteAccountRouteImport } from './routes/settings_/delete-account'
import { Route as SettingsAccountDetailsRouteImport } from './routes/settings_/account-details'
import { Route as GoalsCreateRouteImport } from './routes/goals_/create'
import { Route as GoalsGoalIdRouteImport } from './routes/goals_/$goalId'
import { Route as GoalsGoalIdEditRouteImport } from './routes/goals_/$goalId_.edit'
import { Route as GoalsGoalIdEntriesCreateRouteImport } from './routes/goals_/$goalId_.entries.create'
import { Route as GoalsGoalIdEntriesEntryIdEditRouteImport } from './routes/goals_/$goalId_.entries_.$entryId.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrysRoute = EntrysRouteImport.update({
  id: '/entrys',
  path: '/entrys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GoalsRoute,
} as any)
const EntrysIndexRoute = EntrysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntrysRoute,
} as any)
const SettingsGoalVisibilityRoute = SettingsGoalVisibilityRouteImport.update({
  id: '/settings_/goal-visibility',
  path: '/settings/goal-visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGoalOrderRoute = SettingsGoalOrderRouteImport.update({
  id: '/settings_/goal-order',
  path: '/settings/goal-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDeleteAccountRoute = SettingsDeleteAccountRouteImport.update({
  id: '/settings_/delete-account',
  path: '/settings/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountDetailsRoute = SettingsAccountDetailsRouteImport.update({
  id: '/settings_/account-details',
  path: '/settings/account-details',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsCreateRoute = GoalsCreateRouteImport.update({
  id: '/goals_/create',
  path: '/goals/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/goals_/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdEditRoute = GoalsGoalIdEditRouteImport.update({
  id: '/goals_/$goalId_/edit',
  path: '/goals/$goalId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdEntriesCreateRoute =
  GoalsGoalIdEntriesCreateRouteImport.update({
    id: '/goals_/$goalId_/entries/create',
    path: '/goals/$goalId/entries/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const GoalsGoalIdEntriesEntryIdEditRoute =
  GoalsGoalIdEntriesEntryIdEditRouteImport.update({
    id: '/goals_/$goalId_/entries_/$entryId/edit',
    path: '/goals/$goalId/entries/$entryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrys': typeof EntrysRouteWithChildren
  '/goals': typeof GoalsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals/create': typeof GoalsCreateRoute
  '/settings/account-details': typeof SettingsAccountDetailsRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/settings/goal-order': typeof SettingsGoalOrderRoute
  '/settings/goal-visibility': typeof SettingsGoalVisibilityRoute
  '/entrys/': typeof EntrysIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/goals/$goalId/edit': typeof GoalsGoalIdEditRoute
  '/goals/$goalId/entries/create': typeof GoalsGoalIdEntriesCreateRoute
  '/goals/$goalId/entries/$entryId/edit': typeof GoalsGoalIdEntriesEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals/create': typeof GoalsCreateRoute
  '/settings/account-details': typeof SettingsAccountDetailsRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/settings/goal-order': typeof SettingsGoalOrderRoute
  '/settings/goal-visibility': typeof SettingsGoalVisibilityRoute
  '/entrys': typeof EntrysIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/goals/$goalId/edit': typeof GoalsGoalIdEditRoute
  '/goals/$goalId/entries/create': typeof GoalsGoalIdEntriesCreateRoute
  '/goals/$goalId/entries/$entryId/edit': typeof GoalsGoalIdEntriesEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrys': typeof EntrysRouteWithChildren
  '/goals': typeof GoalsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/goals_/$goalId': typeof GoalsGoalIdRoute
  '/goals_/create': typeof GoalsCreateRoute
  '/settings_/account-details': typeof SettingsAccountDetailsRoute
  '/settings_/delete-account': typeof SettingsDeleteAccountRoute
  '/settings_/goal-order': typeof SettingsGoalOrderRoute
  '/settings_/goal-visibility': typeof SettingsGoalVisibilityRoute
  '/entrys/': typeof EntrysIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/goals_/$goalId_/edit': typeof GoalsGoalIdEditRoute
  '/goals_/$goalId_/entries/create': typeof GoalsGoalIdEntriesCreateRoute
  '/goals_/$goalId_/entries_/$entryId/edit': typeof GoalsGoalIdEntriesEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrys'
    | '/goals'
    | '/login'
    | '/settings'
    | '/sign-up'
    | '/goals/$goalId'
    | '/goals/create'
    | '/settings/account-details'
    | '/settings/delete-account'
    | '/settings/goal-order'
    | '/settings/goal-visibility'
    | '/entrys/'
    | '/goals/'
    | '/settings/'
    | '/goals/$goalId/edit'
    | '/goals/$goalId/entries/create'
    | '/goals/$goalId/entries/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/goals/$goalId'
    | '/goals/create'
    | '/settings/account-details'
    | '/settings/delete-account'
    | '/settings/goal-order'
    | '/settings/goal-visibility'
    | '/entrys'
    | '/goals'
    | '/settings'
    | '/goals/$goalId/edit'
    | '/goals/$goalId/entries/create'
    | '/goals/$goalId/entries/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/entrys'
    | '/goals'
    | '/login'
    | '/settings'
    | '/sign-up'
    | '/goals_/$goalId'
    | '/goals_/create'
    | '/settings_/account-details'
    | '/settings_/delete-account'
    | '/settings_/goal-order'
    | '/settings_/goal-visibility'
    | '/entrys/'
    | '/goals/'
    | '/settings/'
    | '/goals_/$goalId_/edit'
    | '/goals_/$goalId_/entries/create'
    | '/goals_/$goalId_/entries_/$entryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrysRoute: typeof EntrysRouteWithChildren
  GoalsRoute: typeof GoalsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
  GoalsCreateRoute: typeof GoalsCreateRoute
  SettingsAccountDetailsRoute: typeof SettingsAccountDetailsRoute
  SettingsDeleteAccountRoute: typeof SettingsDeleteAccountRoute
  SettingsGoalOrderRoute: typeof SettingsGoalOrderRoute
  SettingsGoalVisibilityRoute: typeof SettingsGoalVisibilityRoute
  GoalsGoalIdEditRoute: typeof GoalsGoalIdEditRoute
  GoalsGoalIdEntriesCreateRoute: typeof GoalsGoalIdEntriesCreateRoute
  GoalsGoalIdEntriesEntryIdEditRoute: typeof GoalsGoalIdEntriesEntryIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrys': {
      id: '/entrys'
      path: '/entrys'
      fullPath: '/entrys'
      preLoaderRoute: typeof EntrysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/goals/': {
      id: '/goals/'
      path: '/'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/entrys/': {
      id: '/entrys/'
      path: '/'
      fullPath: '/entrys/'
      preLoaderRoute: typeof EntrysIndexRouteImport
      parentRoute: typeof EntrysRoute
    }
    '/settings_/goal-visibility': {
      id: '/settings_/goal-visibility'
      path: '/settings/goal-visibility'
      fullPath: '/settings/goal-visibility'
      preLoaderRoute: typeof SettingsGoalVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/goal-order': {
      id: '/settings_/goal-order'
      path: '/settings/goal-order'
      fullPath: '/settings/goal-order'
      preLoaderRoute: typeof SettingsGoalOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/delete-account': {
      id: '/settings_/delete-account'
      path: '/settings/delete-account'
      fullPath: '/settings/delete-account'
      preLoaderRoute: typeof SettingsDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/account-details': {
      id: '/settings_/account-details'
      path: '/settings/account-details'
      fullPath: '/settings/account-details'
      preLoaderRoute: typeof SettingsAccountDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/create': {
      id: '/goals_/create'
      path: '/goals/create'
      fullPath: '/goals/create'
      preLoaderRoute: typeof GoalsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/$goalId': {
      id: '/goals_/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/$goalId_/edit': {
      id: '/goals_/$goalId_/edit'
      path: '/goals/$goalId/edit'
      fullPath: '/goals/$goalId/edit'
      preLoaderRoute: typeof GoalsGoalIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/$goalId_/entries/create': {
      id: '/goals_/$goalId_/entries/create'
      path: '/goals/$goalId/entries/create'
      fullPath: '/goals/$goalId/entries/create'
      preLoaderRoute: typeof GoalsGoalIdEntriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals_/$goalId_/entries_/$entryId/edit': {
      id: '/goals_/$goalId_/entries_/$entryId/edit'
      path: '/goals/$goalId/entries/$entryId/edit'
      fullPath: '/goals/$goalId/entries/$entryId/edit'
      preLoaderRoute: typeof GoalsGoalIdEntriesEntryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EntrysRouteChildren {
  EntrysIndexRoute: typeof EntrysIndexRoute
}

const EntrysRouteChildren: EntrysRouteChildren = {
  EntrysIndexRoute: EntrysIndexRoute,
}

const EntrysRouteWithChildren =
  EntrysRoute._addFileChildren(EntrysRouteChildren)

interface GoalsRouteChildren {
  GoalsIndexRoute: typeof GoalsIndexRoute
}

const GoalsRouteChildren: GoalsRouteChildren = {
  GoalsIndexRoute: GoalsIndexRoute,
}

const GoalsRouteWithChildren = GoalsRoute._addFileChildren(GoalsRouteChildren)

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrysRoute: EntrysRouteWithChildren,
  GoalsRoute: GoalsRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignUpRoute: SignUpRoute,
  GoalsGoalIdRoute: GoalsGoalIdRoute,
  GoalsCreateRoute: GoalsCreateRoute,
  SettingsAccountDetailsRoute: SettingsAccountDetailsRoute,
  SettingsDeleteAccountRoute: SettingsDeleteAccountRoute,
  SettingsGoalOrderRoute: SettingsGoalOrderRoute,
  SettingsGoalVisibilityRoute: SettingsGoalVisibilityRoute,
  GoalsGoalIdEditRoute: GoalsGoalIdEditRoute,
  GoalsGoalIdEntriesCreateRoute: GoalsGoalIdEntriesCreateRoute,
  GoalsGoalIdEntriesEntryIdEditRoute: GoalsGoalIdEntriesEntryIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
